### ISSUE TITLE
Flathub website shows outdated version (3.31.1)

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.gnome.clocks#13]
I was avoiding to install this flatpak (I was using the package from Ubuntu repositories instead) because I thought it was outdated and not maintained anymore. Then I looked at the manifest and saw that it's actually the 3.34 version. I don't have much experience but I think flathub website takes the information from the appdata info? Maybe it is a bug there?

**Comment by bilelmoussaoui** [comment]
That was an outdated metainfo, we have got that fixed upstream.
