### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by erickmajor** [flathub/org.gnome.clocks#29]
Nowadays the flatpak app doesn't support dark mode.
Please, add a support for this feature.

**Comment by bilelmoussaoui** [comment]
It definitely does.

**Comment by bilelmoussaoui** [comment]
![image](https://user-images.githubusercontent.com/7660997/161756003-cc1d309a-4d9a-4acb-ae5d-006838119140.png)

![image](https://user-images.githubusercontent.com/7660997/161756046-7b55e6fd-6649-47c0-8727-d20c5c3875a8.png)

**Comment by erickmajor** [comment]
Hi @bilemoussaoui!
This app uses Gtk4, isn't? How to enable this feature in flatpak app?
I had installed the Adwaita theme, but that is available only for Gtk3 theme.

My SO is Ubuntu 20.04.

**Comment by bilelmoussaoui** [comment]
The feature requires a newer GNOME that comes with an appearance setting to switch dark/light style. Unrelated to whatever ubuntu ships with.

**Comment by erickmajor** [comment]
I've researched about this issue in other forums and people related about this problem. For those is related with missing GTK4 themes in flathub repos.
For this reason, this issue occurs in flatpak packages, such as Gnome Clocks app. :(

**Comment by chaserene** [comment]
I have the same issue. my desktop environment uses a dark theme (Adwaita-dark) but it's not GNOME. is there any way I make this version of Clocks dark?
