### ISSUE TITLE
Help is missing

### ISSUE THREAD

**Issue by teohhanhui** [flathub/org.gnome.clocks#44]
> Document Not Found
>
> The URI ‘help:gnome-clocks/index’ does not point to a valid page.
>
> [Search for packages containing this document.](install-help:gnome-clocks)

**Comment by applecuckoo** [comment]
@teohhanhui You should try filing an issue at the [GNOME Clocks GitLab](https://gitlab.gnome.org/GNOME/gnome-clocks/-/issues), this repo is specifically for the flatpak and the actual code is hosted there.

**Comment by teohhanhui** [comment]
The help is only missing when using the flatpak version since it's not being packaged with it.

**Comment by applecuckoo** [comment]
It might be your system, I'm using Linux Mint 21.1 with the flatpak and I'm getting the help page just fine.
![Screenshot from 2023-04-20 19-53-47](https://user-images.githubusercontent.com/113647417/233298856-89561ab2-eda8-4e3b-aa5c-f06e9af3f4f2.png)

**Comment by A6GibKm** [comment]
I am closing as both yelp and the docs are bundled in the flatpak. Please run `flatpak update` maybe `flatpak repair` and see if it persists.

**Comment by teohhanhui** [comment]
For whatever reason it's also working for me now... 😅
