### ISSUE TITLE
Can't run in background

### ISSUE THREAD

**Issue by wi24rd** [flathub/org.gnome.clocks#8]
When I set a alarm and then close the window, the application seems like closed totally, and while it goes to that point I set, it won't work.
It seems like the flatpak version of GNOME evolution is working in background when you closed its window. so maybe we can learn the config of it. I guess just to register some service like in systemd or cron can also work around.
But if it is the problem or function of the orgin program itself, I hope someone can help to forward this to their issue :)

**Comment by bilelmoussaoui** [comment]
That's an upstream issue. It's already reported and we have improved the situation a bit for 3.36
